#!/usr/bin/env bash

# Run Clojure.vim indentation tests

# TODO: colour messages?

pushd "$(dirname "$0")/.."

if [ "$EDITOR" != 'vim' ] && [ "$EDITOR" != 'nvim' ]; then
    echo 'ERROR: Set the "EDITOR" environment variable to "vim" or "nvim" and run again.'
    exit 1
fi

if [ "$EDITOR" = 'vim' ]; then
    editor_opts=('--not-a-term')
else
    editor_opts=()
fi

PASSED=()
FAILED=()
SKIPPED=()

tmp_base_dir='/tmp/clojure.vim/indent'
mkdir -p "$tmp_base_dir"
tmp_dir="$(mktemp --directory "$tmp_base_dir/XXXXXX")"
test_case_dir='tests'

test_pass() { PASSED+=("$1"); echo '::endgroup::'; }
test_fail() {
    FAILED+=("$1")
    echo '::endgroup::'
    echo "::error file=dev/$test_case_dir/$1/out.clj::Failed indent test case."
}
test_skip() {
    SKIPPED+=("$1")
    echo '::endgroup::'
    echo "::warning file=dev/$test_case_dir/$1/out.clj::Skipped indent test case."
}

run_test_case() {
    test_case="$1"
    in_file="$test_case_dir/$test_case/in.clj"
    expected_file="$test_case_dir/$test_case/out.clj"

    echo "::group::$EDITOR: $test_case"

    if [ -f "$test_case_dir/$test_case/SKIP" ]; then
        test_skip "$test_case"
    else
        actual_file="$tmp_dir/$test_case.clj"
        cp "$in_file" "$actual_file"

        # Override the default test commands with a `test.vim` file.
        test_script="$test_case_dir/$test_case/test.vim"
        if [ -f "$test_script" ]; then
            test_cmd=('-S' "$test_script")
        else
            test_cmd=('+normal! gg=G')
        fi

        "$EDITOR" "${editor_opts[@]}" --clean -NXnu test-vimrc.vim "${test_cmd[@]}" '+xall!' -- "$actual_file"

        diff --color=always -u "$expected_file" "$actual_file"

        [ $? -eq 0 ] && test_pass "$test_case" || test_fail "$test_case"
    fi
}

for tcase in $test_case_dir/*/; do
    run_test_case "$(basename "$tcase")"
done

echo "passed: ${#PASSED[@]}, failed: ${#FAILED[@]}, skipped: ${#SKIPPED[@]}"

# If none passed, or some failed, exit with error.
if [ ${#PASSED[@]} -eq 0 ] || [ ${#FAILED[@]} -gt 0 ]; then
    exit 1
fi
